In [1]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [2]:
import gensim.downloader as api

w_vec=api.load("word2vec-google-news-300")


In [3]:
king_vec=w_vec["king"]

In [4]:
king_vec

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [5]:
import pandas as pd
import re
# messages = pd.read_csv(r"E:\learning\krishudemy\nlpml\bagofwords\spam.csv", encoding='latin1')
messages=pd.read_csv(r"E:\learning\krishudemy\nlpml\spamhap\cleaned_spam_data.csv", encoding='latin1')


In [6]:
messages.shape

(5572, 2)

In [7]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\krish\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [8]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [9]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review] # no stopwords 
    review=' '.join(review)
    corpus.append(review)

In [10]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [11]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess # converts a doc into a list of lowercase tokens and ignores token which are too short and long.


In [12]:
words=[]
for sentences in corpus:
    sent_token=sent_tokenize(sentences)
    for sentences in sent_token:
        words.append(simple_preprocess(sentences))

In [13]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [14]:
## Train the Word2Vec Model from Scratch

import gensim
model=gensim.models.Word2Vec(words)

In [15]:
## to get all the vocabulary

model.wv.index_to_key

['you',
 'to',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'be',
 'if',
 'will',
 'ur',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'how',
 'go',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'out',
 'all',
 'know',
 'll',
 'come',
 'like',
 'time',
 'good',
 'then',
 'am',
 'got',
 'wa',
 'there',
 'he',
 'text',
 'only',
 'love',
 'want',
 'send',
 'need',
 'txt',
 'one',
 'today',
 'by',
 'going',
 'don',
 'home',
 'stop',
 'about',
 'she',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'our',
 'think',
 'dont',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'they',
 'her',
 'any',
 'pls',
 'ha',
 'please',
 'co',
 'did',
 'msg',
 'been',
 'min',
 'some',
 'an',
 'make',
 'dear',
 'here',
 'night',
 'who',
 'message',
 'say',
 'well',
 're',
 'where',
 'thing',
 'much',
 'clai

In [16]:
model.corpus_count

5569

In [17]:
model.epochs # default value is 5 epochs

5

In [18]:
model.wv.similar_by_word('kid')

[('nice', 0.9977626800537109),
 ('even', 0.9976288080215454),
 ('leh', 0.9975582361221313),
 ('im', 0.9975242614746094),
 ('until', 0.9975229501724243),
 ('guess', 0.9975187182426453),
 ('done', 0.997495710849762),
 ('life', 0.9974943399429321),
 ('went', 0.9974929690361023),
 ('people', 0.9974657893180847)]

In [19]:
model.wv['kid']

array([-0.0610843 ,  0.11218305,  0.04230744,  0.02387595,  0.04603973,
       -0.16488828,  0.04000981,  0.25120413, -0.08060166, -0.03712246,
       -0.05141636, -0.1662663 , -0.03548424,  0.05720965,  0.02542195,
       -0.08626643,  0.03458598, -0.14915203, -0.01098103, -0.1860184 ,
        0.07556873,  0.07181389,  0.11958949, -0.04525503,  0.00936452,
        0.02278729, -0.08338029, -0.1167248 , -0.10579646,  0.04156114,
        0.1239856 ,  0.00954064,  0.04923701, -0.09813133, -0.0749618 ,
        0.13160038,  0.00808971, -0.09186165, -0.06523222, -0.20119861,
        0.03398997, -0.05363531, -0.08113687,  0.0081479 ,  0.0787185 ,
       -0.04809305, -0.07186548, -0.05831265,  0.02685937,  0.07309939,
        0.0620948 , -0.09475829, -0.00559415, -0.00099722, -0.06416216,
        0.06294539,  0.06851179,  0.03111947, -0.15043336,  0.09187616,
        0.03042818,  0.01913797,  0.00330563, -0.04780473, -0.12138209,
        0.11285118,  0.03568445,  0.07391006, -0.14360346,  0.12

In [20]:
model.wv['kid'].shape

(100,)

In [21]:
model.wv.similar_by_word('good')

[('day', 0.9990599155426025),
 ('happy', 0.9989027380943298),
 ('dear', 0.99873948097229),
 ('morning', 0.9985786080360413),
 ('where', 0.9985761046409607),
 ('hope', 0.9985042810440063),
 ('amp', 0.99849933385849),
 ('all', 0.9984943866729736),
 ('well', 0.9984665513038635),
 ('night', 0.9984102249145508)]

In [22]:
model.wv['good']

array([-0.23997347,  0.36435932,  0.13955802,  0.08707273,  0.12899037,
       -0.5496304 ,  0.18394023,  0.878725  , -0.26374868, -0.17364144,
       -0.1216718 , -0.5953189 , -0.14502351,  0.17100264,  0.11601899,
       -0.2899951 ,  0.12094652, -0.4931864 , -0.0099773 , -0.66043335,
        0.2981538 ,  0.31916812,  0.38093433, -0.21421583,  0.01551182,
        0.05474228, -0.29426977, -0.4186693 , -0.39618474,  0.11216841,
        0.48688617,  0.0035623 ,  0.2095271 , -0.36915553, -0.31041256,
        0.47631463,  0.06030646, -0.29925844, -0.21486948, -0.6772677 ,
        0.12506448, -0.19428211, -0.2824462 , -0.00391533,  0.31036043,
       -0.14001682, -0.26876074, -0.19780746,  0.10578976,  0.28616434,
        0.21234597, -0.30727568, -0.04512281,  0.00766768, -0.24802575,
        0.18352978,  0.28736225,  0.16018586, -0.4738195 ,  0.33432266,
        0.11972648,  0.05269365, -0.03663648, -0.2026026 , -0.46784574,
        0.38087568,  0.13456532,  0.26462495, -0.53519654,  0.42

In [23]:
model.wv['good'].shape

(100,)

In [24]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [25]:
words[1]

['ok', 'lar', 'joking', 'wif', 'oni']

## Average Word2Vec

In [26]:
import numpy as np

In [27]:
# def avg_word2vec(doc):
#     # remove out-of-vocabulary words
#     sentence_vectors = [word for word in doc if word in model.wv.index_to_key]
#     print(sent)
    
#     return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key], axis=0)
#                 #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [28]:
import numpy as np
from tqdm import tqdm

def avg_word2vec(doc, model):
    """
    Calculates the average Word2Vec vector for a document (list of words).
    Returns a zero vector if no words are in the model's vocabulary.
    """
    # Get all word vectors for words that exist in the model's vocabulary
    sentence_vectors = [model.wv[word] for word in doc if word in model.wv.index_to_key]
    
    # If no words were found in the vocabulary, return a zero vector of the correct size
    if not sentence_vectors:
        return np.zeros(model.wv.vector_size)
    
    # Otherwise, return the mean of the word vectors
    return np.mean(sentence_vectors, axis=0)

# Apply the corrected function to every sentence in your 'words' list.
# This creates a clean list where every element is a vector of the same size.
X = [avg_word2vec(sentence, model) for sentence in tqdm(words)]

# Now, you can safely convert this to a NumPy array
X_new = np.array(X)

# Check the final shape to confirm it's a proper 2D array (samples, features)
print("\nShape of the final feature matrix:", X_new.shape)


100%|██████████| 5569/5569 [00:00<00:00, 13996.51it/s]


Shape of the final feature matrix: (5569, 100)


In [29]:
from tqdm import tqdm 

In [30]:
# ## applying avg for the entire sentences

# X=[]
# for i in tqdm(range(len(words))):
#     print('Hello', i)
#     X.append(avg_word2vec(words[i]))

In [31]:
X

[array([-0.1679442 ,  0.26413485,  0.09691399,  0.07467929,  0.08857051,
        -0.36722282,  0.10288801,  0.59471816, -0.2035494 , -0.10759828,
        -0.10430052, -0.3876666 , -0.07246949,  0.12433629,  0.07647484,
        -0.20536973,  0.08404899, -0.34054917, -0.00892432, -0.4719482 ,
         0.19963479,  0.19209132,  0.26742652, -0.12919053,  0.00679092,
         0.06820191, -0.20846353, -0.2787503 , -0.26648057,  0.09315248,
         0.31390736,  0.00109259,  0.11877055, -0.26510587, -0.20199205,
         0.33498588,  0.03262289, -0.20426616, -0.15482202, -0.47141817,
         0.07103939, -0.14851262, -0.2042012 ,  0.00651968,  0.21125704,
        -0.10120904, -0.17477813, -0.14784497,  0.0793732 ,  0.18474714,
         0.12937683, -0.22731347, -0.03583031,  0.00153392, -0.16917726,
         0.12503195,  0.17728287,  0.09910919, -0.3428951 ,  0.23344268,
         0.08437464,  0.03468287, -0.00966014, -0.1323931 , -0.31031227,
         0.27210838,  0.08833261,  0.19830674, -0.3

In [32]:
len(X)

5569

In [33]:
# # indepedent features

# X_new=np.array(X)

In [34]:
# indepedent features

def avg_word2vec(doc, model):
    # Get all word vectors for words that exist in the model's vocabulary
    sentence_vectors = [model.wv[word] for word in doc if word in model.wv.index_to_key]
    
    # If no words were found in the vocabulary, return a zero vector
    if not sentence_vectors:
        return np.zeros(model.wv.vector_size)
    
    # Otherwise, return the mean of the word vectors
    return np.mean(sentence_vectors, axis=0)

# Apply the function to every sentence in your 'words' list
# This creates a clean list where every element is a vector of the same size
X = [avg_word2vec(sentence, model) for sentence in tqdm(words)]

# Now, you can safely convert this to a NumPy array
X_new = np.array(X)

# Check the final shape to confirm it's correct
print("\nShape of the final feature matrix:", X_new.shape)


100%|██████████| 5569/5569 [00:00<00:00, 12669.67it/s]


Shape of the final feature matrix: (5569, 100)


In [35]:

messages.shape

(5572, 2)

In [36]:
X[1]

array([-0.15581264,  0.22656918,  0.08107396,  0.06197829,  0.08092412,
       -0.31336838,  0.08043071,  0.5090914 , -0.16844815, -0.09269394,
       -0.09425091, -0.326315  , -0.06105704,  0.11559919,  0.0633219 ,
       -0.1813575 ,  0.07691748, -0.2956218 , -0.01873341, -0.41316363,
        0.17395455,  0.16158761,  0.2222785 , -0.10773674,  0.00978383,
        0.04996238, -0.17791978, -0.24364415, -0.227601  ,  0.08122662,
        0.2703624 , -0.00338426,  0.08837742, -0.23348987, -0.17540982,
        0.2861309 ,  0.01456435, -0.17944302, -0.12923703, -0.4148283 ,
        0.06750594, -0.12982981, -0.1719732 , -0.00068528,  0.17157385,
       -0.08581752, -0.14684972, -0.12228236,  0.06889624,  0.16072136,
        0.11081979, -0.19417287, -0.02725348,  0.0042639 , -0.14490873,
        0.10933895,  0.15231374,  0.07936046, -0.3004207 ,  0.20655222,
        0.07367537,  0.02541305, -0.01038081, -0.11190981, -0.27267134,
        0.2265096 ,  0.07195614,  0.16711718, -0.30295542,  0.26

In [37]:
messages.shape

(5572, 2)

In [38]:
X_new.shape

(5569, 100)

In [39]:
X_new[0]

array([-0.16794419,  0.26413485,  0.09691399,  0.07467929,  0.08857051,
       -0.36722282,  0.10288801,  0.59471816, -0.2035494 , -0.10759828,
       -0.10430052, -0.38766661, -0.07246949,  0.12433629,  0.07647484,
       -0.20536973,  0.08404899, -0.34054917, -0.00892432, -0.47194821,
        0.19963479,  0.19209132,  0.26742652, -0.12919053,  0.00679092,
        0.06820191, -0.20846353, -0.2787503 , -0.26648057,  0.09315248,
        0.31390736,  0.00109259,  0.11877055, -0.26510587, -0.20199205,
        0.33498588,  0.03262289, -0.20426616, -0.15482202, -0.47141817,
        0.07103939, -0.14851262, -0.20420121,  0.00651968,  0.21125704,
       -0.10120904, -0.17477813, -0.14784497,  0.0793732 ,  0.18474714,
        0.12937683, -0.22731347, -0.03583031,  0.00153392, -0.16917726,
        0.12503195,  0.17728287,  0.09910919, -0.34289509,  0.23344268,
        0.08437464,  0.03468287, -0.00966014, -0.13239311, -0.31031227,
        0.27210838,  0.08833261,  0.19830674, -0.3618618 ,  0.29

In [40]:
X_new[0].shape

(100,)

In [41]:
## Dependent Features
## Output Features
y = messages[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(y['target'])
y=y.iloc[:,0].values

In [42]:
y.shape

(5569,)

In [43]:
## this is the final independent features
df=pd.DataFrame(X)

In [44]:
df.head()

0         1         2         3         4         5         6   \
0 -0.167944  0.264135  0.096914  0.074679  0.088571 -0.367223  0.102888   
1 -0.155813  0.226569  0.081074  0.061978  0.080924 -0.313368  0.080431   
2 -0.197467  0.278670  0.145249  0.119910  0.103238 -0.410774  0.093820   
3 -0.236348  0.354166  0.116156  0.092157  0.117862 -0.493405  0.130669   
4 -0.192963  0.292906  0.108721  0.073259  0.111747 -0.417745  0.109710   

         7         8         9   ...        90        91        92        93  \
0  0.594718 -0.203549 -0.107598  ...  0.357371  0.171893  0.006737  0.081746   
1  0.509091 -0.168448 -0.092694  ...  0.315038  0.139645  0.010288  0.072727   
2  0.640681 -0.255259 -0.113360  ...  0.388023  0.157746 -0.006466  0.089573   
3  0.808206 -0.258654 -0.143660  ...  0.480933  0.226699  0.015390  0.125115   
4  0.679711 -0.227475 -0.128093  ...  0.403179  0.186381  0.007695  0.101420   

         94        95        96        97        98        99  
0  0.458455  0.260192  0.143645 -0.101744  0.076483 -0.106561  
1  0.382429  0.221776  0.129132 -0.102335  0.068887 -0.092608  
2  0.461395  0.257203  0.138580 -0.108681  0.076480 -0.091443  
3  0.615615  0.351769  0.200423 -0.146104  0.099954 -0.139713  
4  0.514620  0.297744  0.155709 -0.133398  0.081069 -0.122630  

[5 rows x 100 columns]

In [45]:
df.shape

(5569, 100)

In [46]:
## independent feature 
X=df

In [47]:
X.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [48]:
y

array([ True,  True, False, ...,  True,  True,  True])

In [49]:
y.shape

(5569,)

In [69]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.20, random_state=0)

In [70]:
X_train.head()

0         1         2         3         4         5         6   \
253  -0.228610  0.345270  0.138387  0.090176  0.131298 -0.495446  0.132011   
1114 -0.211050  0.326568  0.120084  0.092119  0.111308 -0.452649  0.128575   
4613 -0.111376  0.180334  0.066329  0.049569  0.066597 -0.258865  0.072625   
4376 -0.219088  0.330029  0.137827  0.066167  0.138157 -0.502212  0.132238   
1012 -0.152322  0.232463  0.086554  0.062686  0.083301 -0.322854  0.084668   

            7         8         9   ...        90        91        92  \
253   0.797893 -0.279466 -0.146331  ...  0.466073  0.219070  0.004958   
1114  0.739809 -0.258777 -0.135139  ...  0.430905  0.214508  0.010873   
4613  0.408004 -0.143852 -0.069792  ...  0.243018  0.108618  0.009734   
4376  0.806616 -0.265130 -0.159157  ...  0.472842  0.219773 -0.001609   
1012  0.529410 -0.176406 -0.091097  ...  0.316637  0.145680  0.006602   

            93        94        95        96        97        98        99  
253   0.107804  0.598875  0.343943  0.181507 -0.142654  0.097055 -0.133917  
1114  0.100385  0.569418  0.325921  0.186924 -0.122489  0.099959 -0.138207  
4613  0.055656  0.311839  0.179027  0.103904 -0.072134  0.048621 -0.075201  
4376  0.111628  0.593377  0.362673  0.153179 -0.168984  0.099625 -0.125448  
1012  0.074192  0.396125  0.226476  0.121915 -0.095977  0.066752 -0.092181  

[5 rows x 100 columns]

In [71]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [72]:
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [73]:
y_pred=classifier.predict(X_test)

In [74]:
from sklearn.metrics import accuracy_score, classification_report

In [66]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.91      0.84      0.87       151
        True       0.98      0.99      0.98       963

    accuracy                           0.97      1114
   macro avg       0.94      0.91      0.93      1114
weighted avg       0.97      0.97      0.97      1114

