In [27]:
import numpy as np
import pandas as pd
import os

# print(os.getcwd())

messages = pd.read_csv(r"E:\learning\krishudemy\nlpml\bagofwords\spam.csv", encoding='latin1')

In [39]:
## data preprocessing

messages = pd.read_csv(r"E:\learning\krishudemy\nlpml\bagofwords\spam.csv", encoding='latin1')
messages.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [40]:
messages.shape

(5572, 5)

In [41]:
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [42]:
messages.drop(columns=["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], inplace=True)

In [43]:
messages.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [44]:
messages.rename(columns={"v1":"target", "v2":"message"}, inplace=True)

In [45]:
messages.head()

target                                            message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [46]:
## text cleaning

import re
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\krish\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [49]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
porter_stemmer=PorterStemmer()

In [79]:
## PorterS Stemming

corpus_porter=[]

for i in range(0, len(messages)):
    review=re.sub("[^a-zA-z]",' ', messages['message'][i]) # remove special characters
    review=review.lower() # lower teh words
    review=review.split()  # slipt and get a list of words
    review=[porter_stemmer.stem(word) for word in review if not word in stopwords.words('english')] #
    review=" ".join(review)
    corpus_porter.append(review)

In [81]:
corpus_porter

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [63]:
## snowball stemming

from nltk.stem import SnowballStemmer
snowball_stemmer=SnowballStemmer("english")

In [83]:
corpus_snowball=[]

for i in range(0, len(messages)):
    review=re.sub("[^a-zA-z]",' ', messages['message'][i]) # remove special characters
    review=review.lower() # lower teh words
    review=review.split()  # slipt and get a list of words
    review=[snowball_stemmer.stem(word) for word in review if not word in stopwords.words('english')] #
    review=" ".join(review)
    corpus_snowball.append(review)

In [84]:
corpus_snowball

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkts st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breath

In [70]:
>>> import nltk
>>> nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\krish\AppData\Roaming\nltk_data...


True

In [71]:
## lemmatization

from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [85]:
corpus_lematizer=[]

for i in range(0, len(messages)):
    review=re.sub("[^a-zA-z]",' ', messages['message'][i]) # remove special characters
    review=review.lower() # lower teh words
    review=review.split()  # slipt and get a list of words
    review=[lemmatizer.lemmatize(word, pos='v') for word in review if not word in stopwords.words('english')] #
    review=" ".join(review)
    corpus_lematizer.append(review)

In [86]:
corpus_lematizer

['go jurong point crazy available bugis n great world la e buffet cine get amore wat',
 'ok lar joke wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf live around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'winner value network customer select receivea prize reward claim call claim code kl valid hours',
 'mobile months u r entitle update latest colour mobiles camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cry enough today',
 'six chance win cash pound txt csh send cost p day days tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',


## create the bag of words 

In [107]:
### create the bag of words 

from sklearn.feature_extraction.text import CountVectorizer

# for binary bow to enable binary=True
count_vectorizer=CountVectorizer(max_features=100, binary=True) # normal binary bow

In [108]:
X=count_vectorizer.fit_transform(corpus_lematizer).toarray()

In [109]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [110]:
X.shape

(5572, 100)

In [122]:
#### N-Grams

count_vectorizer.vocabulary_

{'go': np.int64(24),
 'great': np.int64(26),
 'get': np.int64(22),
 'wat': np.int64(91),
 'ok': np.int64(59),
 'free': np.int64(21),
 'win': np.int64(95),
 'text': np.int64(79),
 'txt': np.int64(86),
 'say': np.int64(69),
 'already': np.int64(0),
 'think': np.int64(81),
 'hey': np.int64(29),
 'week': np.int64(93),
 'back': np.int64(4),
 'like': np.int64(40),
 'still': np.int64(75),
 'send': np.int64(71),
 'even': np.int64(18),
 'prize': np.int64(65),
 'claim': np.int64(9),
 'call': np.int64(6),
 'mobile': np.int64(50),
 'home': np.int64(31),
 'want': np.int64(90),
 'today': np.int64(83),
 'cash': np.int64(8),
 'day': np.int64(15),
 'reply': np.int64(67),
 'www': np.int64(97),
 'right': np.int64(68),
 'thank': np.int64(80),
 'take': np.int64(77),
 'time': np.int64(82),
 'use': np.int64(88),
 'message': np.int64(48),
 'com': np.int64(10),
 'oh': np.int64(58),
 'yes': np.int64(99),
 'make': np.int64(46),
 'way': np.int64(92),
 'feel': np.int64(19),
 'dont': np.int64(17),
 'miss': np.int64

In [ ]:
### create the bag of words model with N-Grams (Unigram)

from sklearn.feature_extraction.text import CountVectorizer

# for binary bow to enable binary=True
count_vectorizer=CountVectorizer(max_features=500, binary=True, ngram_range=(1,1)) # normal binary bow with unigram


In [124]:
X=count_vectorizer.fit_transform(corpus_lematizer).toarray()

In [125]:
count_vectorizer.vocabulary_

{'go': np.int64(159),
 'point': np.int64(327),
 'available': np.int64(24),
 'great': np.int64(165),
 'world': np.int64(483),
 'get': np.int64(155),
 'wat': np.int64(463),
 'ok': np.int64(295),
 'lar': np.int64(216),
 'wif': np.int64(472),
 'free': np.int64(146),
 'entry': np.int64(128),
 'win': np.int64(475),
 'final': np.int64(139),
 'st': np.int64(394),
 'may': np.int64(247),
 'text': np.int64(409),
 'receive': np.int64(348),
 'question': np.int64(339),
 'txt': np.int64(443),
 'rate': np.int64(341),
 'apply': np.int64(19),
 'dun': np.int64(116),
 'say': np.int64(361),
 'early': np.int64(118),
 'already': np.int64(10),
 'think': np.int64(417),
 'live': np.int64(232),
 'around': np.int64(21),
 'though': np.int64(420),
 'hey': np.int64(185),
 'week': np.int64(466),
 'word': np.int64(481),
 'back': np.int64(31),
 'like': np.int64(228),
 'fun': np.int64(152),
 'still': np.int64(397),
 'xxx': np.int64(490),
 'send': np.int64(369),
 'even': np.int64(130),
 'brother': np.int64(48),
 'speak':

In [132]:
### create the bag of words model with N-Grams (bigram)

from sklearn.feature_extraction.text import CountVectorizer

# for binary bow to enable binary=True
count_vectorizer=CountVectorizer(max_features=500, binary=True, ngram_range=(1,2)) # normal binary bow with bigram
X=count_vectorizer.fit_transform(corpus_lematizer).toarray()

In [133]:
count_vectorizer.vocabulary_

{'go': np.int64(162),
 'point': np.int64(333),
 'great': np.int64(170),
 'world': np.int64(483),
 'get': np.int64(158),
 'wat': np.int64(464),
 'ok': np.int64(300),
 'lar': np.int64(221),
 'wif': np.int64(473),
 'free': np.int64(149),
 'entry': np.int64(132),
 'win': np.int64(475),
 'st': np.int64(398),
 'may': np.int64(255),
 'text': np.int64(413),
 'receive': np.int64(353),
 'question': np.int64(345),
 'txt': np.int64(447),
 'rate': np.int64(347),
 'apply': np.int64(19),
 'dun': np.int64(120),
 'say': np.int64(366),
 'early': np.int64(122),
 'already': np.int64(10),
 'think': np.int64(421),
 'live': np.int64(238),
 'around': np.int64(21),
 'though': np.int64(423),
 'hey': np.int64(192),
 'week': np.int64(467),
 'word': np.int64(481),
 'back': np.int64(30),
 'like': np.int64(234),
 'fun': np.int64(156),
 'still': np.int64(401),
 'xxx': np.int64(490),
 'send': np.int64(374),
 'even': np.int64(134),
 'brother': np.int64(47),
 'speak': np.int64(395),
 'treat': np.int64(440),
 'per': np.i

In [134]:
### create the bag of words model with N-Grams (bigram)

from sklearn.feature_extraction.text import CountVectorizer

# for binary bow to enable binary=True
count_vectorizer=CountVectorizer(max_features=500, binary=True, ngram_range=(2,2)) # normal binary bow with bigram igniring unigram
X=count_vectorizer.fit_transform(corpus_lematizer).toarray()

In [135]:
count_vectorizer.vocabulary_

{'free entry': np.int64(128),
 'txt rate': np.int64(429),
 'think go': np.int64(411),
 'per request': np.int64(308),
 'claim call': np.int64(55),
 'call claim': np.int64(25),
 'claim code': np.int64(56),
 'entitle update': np.int64(114),
 'update latest': np.int64(435),
 'latest colour': np.int64(222),
 'free call': np.int64(126),
 'call mobile': np.int64(34),
 'mobile update': np.int64(270),
 'chance win': np.int64(54),
 'win cash': np.int64(477),
 'reply hl': np.int64(346),
 'hl info': np.int64(197),
 'txt word': np.int64(431),
 'dont miss': np.int64(103),
 'let know': np.int64(227),
 'feel like': np.int64(119),
 'yeah get': np.int64(495),
 'mobile charge': np.int64(265),
 'reply yes': np.int64(348),
 'go home': np.int64(155),
 'anything lor': np.int64(5),
 'great weekend': np.int64(172),
 'call reply': np.int64(38),
 'nokia mobile': np.int64(288),
 'mobile free': np.int64(267),
 'free camcorder': np.int64(127),
 'please call': np.int64(314),
 'delivery tomorrow': np.int64(97),
 'lt 

In [ ]:
### create the bag of words model with N-Grams (bigram, trigram)

from sklearn.feature_extraction.text import CountVectorizer

# for binary bow to enable binary=True
count_vectorizer=CountVectorizer(max_features=500, binary=True, ngram_range=(1,3)) # normal binary bow with trigram
X=count_vectorizer.fit_transform(corpus_lematizer).toarray()

In [131]:
count_vectorizer.vocabulary_

{'go': np.int64(161),
 'point': np.int64(332),
 'great': np.int64(168),
 'world': np.int64(483),
 'get': np.int64(157),
 'wat': np.int64(464),
 'ok': np.int64(299),
 'lar': np.int64(220),
 'wif': np.int64(473),
 'free': np.int64(148),
 'entry': np.int64(132),
 'win': np.int64(475),
 'st': np.int64(399),
 'may': np.int64(254),
 'text': np.int64(414),
 'receive': np.int64(353),
 'question': np.int64(345),
 'txt': np.int64(447),
 'rate': np.int64(347),
 'apply': np.int64(19),
 'dun': np.int64(120),
 'say': np.int64(366),
 'early': np.int64(122),
 'already': np.int64(10),
 'think': np.int64(422),
 'live': np.int64(236),
 'around': np.int64(21),
 'though': np.int64(424),
 'hey': np.int64(190),
 'week': np.int64(467),
 'word': np.int64(481),
 'back': np.int64(31),
 'like': np.int64(232),
 'fun': np.int64(155),
 'still': np.int64(402),
 'xxx': np.int64(490),
 'send': np.int64(374),
 'even': np.int64(133),
 'brother': np.int64(48),
 'speak': np.int64(396),
 'per': np.int64(315),
 'set': np.int